<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/20
 * Time: 16:06
 */

namespace backend\filters;


use yii\base\ActionFilter;
use yii\web\HttpException;

class RbacFilter extends ActionFilter
{
    public function beforeAction($action)
    {
        //判断用户是否有权限
        if (!\Yii::$app->user->can($action->uniqueId)) {
            //判定用户是否登录
            if (\Yii::$app->user->isGuest) {
                return $action->controller->redirect(\Yii::$app->user->loginUrl)->send();
            }
            //抛出403异常
            throw new HttpException('403','对不起，您没有该执行权限');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}