<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/22
 * Time: 15:35
 */

namespace frontend\components;

use yii\base\Component;
use Aliyun\Core\Config;
use Aliyun\Core\Profile\DefaultProfile;
use Aliyun\Core\DefaultAcsClient;
use Aliyun\Api\Sms\Request\V20170525\SendSmsRequest;

class Sms extends Component
{
    public $ak;//ak
    public $sk;//sk
    public $sign;//短信签名
    public $template;//短信模板
    public $tel;//发送的手机号码
    public $params = [];//模板中的变量

    private $acsClient;

    public function init()
    {
        // 加载区域结点配置
        Config::load();
        // 短信API产品名
        $product = "Dysmsapi";
        // 短信API产品域名
        $domain = "dysmsapi.aliyuncs.com";
        // 暂时不支持多Region
        $region = "cn-hangzhou";
        // 服务结点
        $endPointName = "cn-hangzhou";
        // 初始化用户Profile实例
        $profile = DefaultProfile::getProfile($region, $this->ak,$this->sk);

        // 增加服务结点
        DefaultProfile::addEndpoint($endPointName, $region, $product, $domain);

        // 初始化AcsClient用于发起请求
        $this->acsClient = new DefaultAcsClient($profile);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function send(){
        // 初始化SendSmsRequest实例用于设置发送短信的参数
        $request = new SendSmsRequest();

        // 必填，设置雉短信接收号码
        $request->setPhoneNumbers($this->number);

        // 必填，设置签名名称
        $request->setSignName($this->sign);

        // 必填，设置模板CODE
        $request->setTemplateCode($this->template);

        // 可选，设置模板参数
        if($this->params) {
            $request->setTemplateParam(json_encode($this->params));
        }
        // 发起访问请求
        $acsResponse = $this->acsClient->getAcsResponse($request);

        // 打印请求结果
        // var_dump($acsResponse);

        return $acsResponse;
    }

    public function setNumber($value){
        $this->number = $value;
        return $this;
    }

    public function setParams(Array $data){
        $this->params = $data;
        return $this;
    }
}