<?php

namespace backend\models;

use frontend\models\Cart;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;

/**
 * This is the model class for table "goods".
 *
 * @property integer $id
 * @property string $name
 * @property string $sn
 * @property string $logo
 * @property integer $goods_category_id
 * @property integer $brand_id
 * @property string $market_price
 * @property string $shop_price
 * @property integer $stock
 * @property integer $is_on_sale
 * @property integer $status
 * @property integer $sort
 * @property integer $create_time
 * @property integer $view_times
 */
class Goods extends \yii\db\ActiveRecord
{
    public $total;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'goods';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'logo', 'goods_category_id', 'brand_id', 'shop_price', 'stock', 'is_on_sale', 'sort'], 'required'],
            [['goods_category_id', 'brand_id', 'stock', 'is_on_sale', 'status', 'sort', 'create_time', 'view_times'], 'integer'],
            [['market_price', 'shop_price'], 'number'],
            [['name', 'sn'], 'string', 'max' => 20],
            [['logo'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '商品名称',
            'sn' => '商品货号',
            'logo' => 'LOGO图片',
            'goods_category_id' => '商品分类',
            'brand_id' => '品牌分类',
            'market_price' => '市场价格',
            'shop_price' => '商品价格',
            'stock' => '商品库存',
            'is_on_sale' => '是否上架出售',
            'status' => '商品状态',
            'sort' => '商品排序',
            'create_time' => '添加时间',
            'view_times' => '浏览次数',
        ];
    }

    //关联商品分类表
    public function getCategory(){
        return $this->hasOne(GoodsCategory::className(),['id'=>'goods_category_id']);
    }

    //关联品牌分类表
    public function getBrand(){
        return $this->hasOne(Brand::className(),['id'=>'brand_id']);
    }

    //返回所有品牌信息
    public static function getBrandTab(){
        return ArrayHelper::map(Brand::find()->all(),'id','name');
    }
    //调用方法返回zTree需要的分类数据
    public static function getCategoryTab(){
        return Json::encode(
            GoodsCategory::find()->select(['id','parent_id','name'])->all()
        );
    }

    //关联商品和商品图片
    public function getGallery()
    {
        return $this->hasMany(GoodsGallery::className(),['goods_id'=>'id']);
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            //添加商品记录表
            $day = date('Yms',time());//获得添加商品时的操作的时间
            $count = GoodsDayCount::find()->where(['day'=>$day])->count();//查询当天添加商品的个数
            $model_day_count = new GoodsDayCount();//创建新商品记录模型
            $model_day_count->day = $day;//设置日期
            $model_day_count->count=$count+1;//设置商品数量
            //记录商品货号
            $this -> sn =$day.str_pad($count+1,4,0,STR_PAD_LEFT);
            $this-> status = 1;
            $this->create_time=time();
            $model_day_count->save();//保存商品添加记录
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getCart()
    {
        return $this->hasOne(Cart::className(),['goods_id'=>'id']);
    }
}
